{% set name = "miniwdl" %}
{% set version = "0.5.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8e878b2c9a5681c5bbe5b9ca07fc65f42c3287923747311984bf206aad9e706f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - miniwdl = WDL.CLI:main

requirements:
  host:
    - pip
    - pbr
    - python >=3.6
    - setuptools
    - docker-py
    - argcomplete
    - coloredlogs
    - lark-parser 0.7.5
    - pygtail >=0.11.0

  run:
    - python >=3.6
    - setuptools
    - docker-py
    - argcomplete
    - coloredlogs
    - lark-parser 0.7.2
    - pygtail >=0.11.0
test:
  imports:
    - WDL
    - WDL.Env
    - WDL.Error
    - WDL.Expr
    - WDL.StdLib
    - WDL.Tree
    - WDL.Type
    - WDL.Value
    - WDL.Walker
  commands:
    - miniwdl --help

about:
  home: "https://github.com/chanzuckerberg/miniwdl"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Developer toolkit for the Workflow Description Language (WDL)"
  description: >
    miniwdl provides WDL developer productivity tools, a local runtime
    implementation, and a foundation for language experimentation.

extra:
  recipe-maintainers:
    - mlin
    - rhpvorderman
