{% set name = "miniwdl" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12e9cec90fc9441b9b03dfbfd159a70c4603b4bec6a5515fdd0e7147b3c74927

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  entry_points:
    - miniwdl = WDL.CLI:main

requirements:
  host:
    - pip
    - pbr
    - python >=3.6
    - setuptools
    - xdg >=2.0.0
    - importlib_metadata >=1.0.0
    - docker-py >=3.4.0
    - regex >=v39.0.1
    - argcomplete >=1.11.0
    - coloredlogs >=11.0
    - pygtail >=0.11.0
    - python-json-logger >=0.1.11
    - ruamel.yaml >=0.15.37
    - lark-parser 0.9.0

  run:
    - python >=3.6
    - setuptools
    - xdg >=2.0.0
    - importlib_metadata >=1.0.0
    - docker-py >=3.4.0
    - regex >=v39.0.1
    - argcomplete >=1.11.0
    - coloredlogs >=11.0
    - pygtail >=0.11.0
    - python-json-logger >=0.1.11
    - ruamel.yaml >=0.15.37
    - lark-parser 0.9.0

test:
  imports:
    - WDL
    - WDL.Env
    - WDL.Error
    - WDL.Expr
    - WDL.StdLib
    - WDL.Tree
    - WDL.Type
    - WDL.Value
    - WDL.Walker
  commands:
    - miniwdl --help

about:
  home: https://github.com/chanzuckerberg/miniwdl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Developer toolkit for the Workflow Description Language (WDL)
  description: >
    miniwdl provides WDL developer productivity tools, a local runtime implementation, and a foundation for language experimentation.

extra:
  recipe-maintainers:
    - mlin
    - rhpvorderman
